name: code-quality

on: [push, pull_request]

jobs:
  code-quality:
    strategy:
      matrix:
        config: [Release]
        os: [ubuntu-20.04]
        language: ['csharp']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set .NET version to use
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'

      - name: Initialise CodeQL
        uses: github/codeql-action/init@v1

      - name: Build
        run: dotnet build -c ${{ matrix.config }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
