name: code-quality

on: [push, pull_request]

jobs:
  code-quality:
    strategy:
      matrix:
        config: [Release]
        os: [ubuntu-20.04]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set .NET version to use
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'

      - name: Build and analyze
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=louisnayegon
            -Dsonar.projectKey=louisnayegon_mcp2221_cli
            -Dsonar.verbose=true
