name: code-quality

on: [push, pull_request]

jobs:
  code-quality:
    strategy:
      matrix:
        config: [Release]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set .NET version to use
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.100'

      - name: Build
        run: dotnet build -c ${{ matrix.config }}

      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@main
        id: code-analysis
        with:
          build-breaking: false

      - name: Upload analysis results
        uses: actions/upload-artifact@v2
        with:
          name: analysis_results.sarif
          path: ${{ steps.code-analysis.outputs.sarifFile }}
